[project]
name = "adventofcode2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.1",
    "z3-solver>=4.15.4.0",
]

[tool.pytest]
python_files = ["*.py"]
